# Generated by Django 4.2.1 on 2023-06-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
